app/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from datetime import datetime

from app import db, login

@login.user_loader
def load_user(user_id):
    return User.query.get(user_id)


class User(UserMixin,db.Model):
    user_id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(20), unique=True, nullable=False)
    password = db.Column(db.String(128), nullable=False)  
    posts = db.relationship('Post', backref='author', lazy=True)
    cars = db.relationship('AddCar', backref='owner', lazy=True)
      
    def __repr__(self):
        return f'User: {self.username}'
    
    def commit(self):
        db.session.add(self)
        db.session.commit()

    def hash_password(self,password):
        return generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)
    
    def get_id(self):
        return str(self.user_id)
    
    
    
class Post(db.Model):
    id=  db.Column(db.Integer, primary_key=True)
    body= db.Column(db.String(250))
    timestamp= db.Column(db.DateTime, default=datetime.utcnow)
    user_id= db.Column(db.Integer, db.ForeignKey('user.user_id'), nullable=False)

    def __repr__(self):
        return f'<Post: {self.body}>'
    
    def commit(self):
        db.session.add(self)
        db.session.commit()
        
class AddCar(db.Model):   
    id= db.Column(db.Integer, primary_key=True)
    make= db.Column(db.String(20), nullable=False)
    model = db.Column(db.String(20), nullable=False)
    year = db.Column(db.String(4), nullable=False)
    info = db.Column(db.String(250))
    user_id= db.Column(db.Integer, db.ForeignKey('user.user_id'), nullable=False)
    
    def __repr__(self):
        return f'<AddCar: {self.make} {self.model} {self.year}'
    
    def commit(self):
        db.session.add(self)
        db.session.commit()
  

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Length, Email

class RegisterForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email(), Length(max=120)])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=6, max=20)])
    submit = SubmitField('Sign Up')
    
class SigninForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=2, max=20)])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=6, max=20)])
    submit = SubmitField('Sign In')
    

class PostForm(FlaskForm):
    body = StringField('Input you car information', validators=[DataRequired()])
    submit = SubmitField('Publish')
    
    
class CommentForm(FlaskForm):
    body = StringField("Input car's information you like to add to my collection", validators=[DataRequired()])
    submit = SubmitField('Publish')
    
    
class AddCarForm(FlaskForm):
    make = StringField('Make', validators=[DataRequired(), Length(min=2, max=20)])
    model = StringField('Model', validators=[DataRequired(), Length(min=2, max=20)])
    year = StringField('Year', validators=[DataRequired(), Length(min=4, max=4)])
    info = StringField('Info', validators=[DataRequired(), Length(max=250)])
    submit = SubmitField('Add Car')

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

app = Flask(__name__)
app.config.from_object(Config)
db = SQLAlchemy(app)
migrate = Migrate(app, db)
login = LoginManager(app)

login.login_view = 'auth.signin'
login.login_message = 'Please sign in to access this page.'
login.login_message_category = 'info'

from app.blueprints.auth import bp as auth_bp
app.register_blueprint(auth_bp)
from app.blueprints.main import bp as main_bp
app.register_blueprint(main_bp)
from app.blueprints.social import bp as social_bp
app.register_blueprint(social_bp)
from app.blueprints.api import bp as api_bp
app.register_blueprint(api_bp)

app/blueprints/api/__init__.py
from flask import Blueprint

bp = Blueprint('api', __name__, url_prefix='/api')

from app.blueprints.api import routes, auth_routes

app/blueprints/api/routes.py
from flask import request, jsonify, url_for, g, abort

from . import bp

from app.models import Post, User

#Recieve All Posts
@bp.get('/posts')
def api_posts():
    result = []
    for post in Post.query.all():
        result.append({
            'body': post.body,
            'author': post.author.username,
            'user_id': post.user_id,
            'post_id': post.id,
            'timestamp': post.timestamp,
        })
    return jsonify(result) 

#Recieve Post by specific username
@bp.get('/posts/<username>')
def api_posts_by_username(username):
    user = User.query.filter_by(username=username).first_or_404()
    return jsonify([{
            'body': post.body,
            'author': post.author.username,
            'user_id': post.user_id,
            'post_id': post.id,
            'timestamp': post.timestamp,
        }for post in user.posts])

#Send a single post
@bp.get('/posts/<int:id>')
def api_post(id):
    post = Post.query.get_or_404(id)
    return jsonify({
            'body': post.body,
            'author': post.author.username,
            'user_id': post.user_id,
            'post_id': post.id,
            'timestamp': post.timestamp,
        })
    

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.blueprints.main import routes

app/blueprints/main/routes.py
from . import bp as app
from flask import render_template
from flask_login import login_required
from app.forms import PostForm 


@app.route('/')
@app.route('/home')
def home():
    return render_template('home.jinja', title='Home')

@app.route('/about')
def about():
    return render_template('about.jinja', title='About')

app/blueprints/social/__init__.py
from flask import Blueprint

bp = Blueprint('social', __name__, url_prefix='/social')

from . import routes

app/blueprints/social/routes.py
from . import bp
from app.forms import PostForm, CommentForm, AddCarForm
from app.models import Post, User, AddCar
from flask_login import current_user, login_required
from flask import render_template, flash, redirect, url_for


@bp.route('/post', methods=['GET','POST'])
@login_required
def post():
    form = PostForm()
    if form.validate_on_submit():
        p = Post(body=form.body.data)
        p.id = Post.query.count() + 1
        p.user_id = current_user.user_id
        p.commit()
        flash('Published', 'success')
        return redirect(url_for('social.user_page', username=current_user.username))
    return render_template('post.jinja', form = form)


@bp.route('/comments', methods=['GET','POST'])
@login_required
def comments():
    form = CommentForm()
    if form.validate_on_submit():
        p = Post(body=form.body.data)
        p.id = Post.query.count() + 1
        p.user_id = 5 #my admin userid
        p.commit()
        flash('Added to my collection!', 'success')
    return render_template('comments.jinja', form = form)
        
@bp.route('/userpage/<username>')
def user_page(username):   
    user = User.query.filter_by(username=username).first()
    return render_template('user_page.jinja', title= f"{username}'s page" ,user=user)

@bp.route('/addcar', methods=['GET','POST'])
@login_required
def addcar():
    form = AddCarForm()
    if form.validate_on_submit():
        c = AddCar(make=form.make.data, model=form.model.data, year=form.year.data, info=form.info.data)
        c.user_id = current_user.user_id
        print(c.user_id)
        c.commit()
        flash('Added to car collection!', 'success')
        return redirect(url_for('social.user_page', username=current_user.username))
    return render_template('add_car.jinja', form=form)
    

app/templates/about.jinja
{% extends 'base.jinja' %}
{% block content %}
    <h1>about</h1>
   
{% endblock %}

app/templates/add_car.jinja
{% extends "base.jinja" %}

{% block content %}
  <h2>Add Car</h2>
  <form action="" method="post">
  {{ form.hidden_tag() }}
 <p>
    {{ form.make.label }}
    {{ form.make(size=32) }} <br>
    {{ form.model.label }}
    {{ form.model(size=32) }} <br>
    {{ form.year.label }}
    {{ form.year(size=32) }} <br>
    {% for error in form.year.errors %}
      <span class="err-msg">{{ error }}</span>
    {% endfor %}
    {{ form.info.label }}
    {{ form.info(size=32) }} <br>
 </p>
 <p>{{ form.submit() }}</p>
</form>
{% endblock content %}

app/templates/base.jinja
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{{url_for('static', filename='main.css')}}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
  {% if title %}
  <title>{{ title }}</title>
  {% else %}
  {% endif %}
</head>
<body class="container">
  {% include "navbar.jinja" %}

  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
  <ul>
  {% for category, message in messages %}
    <li class="alert alert-{{ category }} alert-dismissible fade show" role="alert">{{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </li>
  {% endfor %}
  </ul>
  {% endif %}
  {%  endwith %}
  {% if current_user.is_authenticated %}
  <p>Logging in as: {{ current_user.username }}</p>
  
  {% else %}
  {% endif %}
  {% block content %}{% endblock %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>  

app/templates/comments.jinja
{% extends "base.jinja" %}
{% block content %}
<div class="form">
    <div class = "content-section">
        <form action="" method="POST">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
            <div class="form-group">
                {{form.body.label(class="form-control-label")}}
                {{form.body(class="form-control form-control-lg")}}
            </div>
            </fieldset>
            <div class="form-group">
                {{form.submit(class="btn btn-outline-info")}}
            </div>
        </form>
    </div>
</div>
{% endblock content %}

app/templates/home.jinja
{% extends 'base.jinja' %}
{% block content %}
    <h1>home</h1>
    
{% endblock %}

app/templates/navbar.jinja
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">My Project</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('main.home')}}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('main.about')}}">About</a>
          </li>
          {% if not current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('auth.register')}}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('auth.signin')}}">Signin</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('social.post')}}">Post</a>
            <li class="nav-item">
            <a class="nav-link" href="{{url_for('social.addcar')}}">Add Car</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('social.user_page', username=current_user.username)}}">My Page</a>
          </li>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('auth.signout')}}">Sign Out</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

app/templates/post.jinja
{% extends "base.jinja" %}

{% block content %}
  <h2>Post</h2>
  <form action="" method="post">
  {{ form.hidden_tag() }}
 <p>
    {{ form.body.label }}<br>
    {{ form.body(size=32) }}
    {% for error in form.body.errors %}
      <span class="err-msg">{{ error }}</span>
    {% endfor %}
 </p>
 <p>{{ form.submit() }}</p>
</form>
{% endblock content %}

app/templates/register.jinja
{% extends "base.jinja" %}
{% block content %}
    <h1>Sign Up For Free Today</h1>
    
        <form action="" method="POST">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
            <div class="form-group">
                {{form.username.label(class="form-control-label")}}
                {% for error in form.email.errors %}
                <span style="color: red;">{{error}}</span>
                {% endfor %}
                {{form.username(class="form-control form-control-lg")}}
            </div>
            <div class="form-group">
                {{form.email.label(class="form-control-label")}}
                {{form.email(class="form-control form-control-lg")}}
            </div>
            <div class="form-group">
                {{form.password.label(class="form-control-label")}}
                {{form.password(class="form-control form-control-lg")}}
            </div>

            </fieldset>
            <div class="form-group">
                {{form.submit(class="btn btn-outline-info")}}
            </div>
        </form>
    </div>

    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{{url_for('auth.signin')}}">Sign In</a>
        </small>
    </div>
{% endblock content %}

app/templates/signin.jinja
{% extends "base.jinja" %}
{% block content %}
<div class="form">
    <h1>Sign In</h1>
    <div class = "content-section">
        <form action="" method="POST">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
            <div class = "form-group">
                {{form.username.label(class="form-control-label")}}
                {{form.username(class="form-control form-control-lg")}}
            </div>
            <div class="form-group">
                {{form.password.label(class="form-control-label")}}
                {{form.password(class="form-control form-control-lg")}}
            </div>
            </fieldset>
            <div class="form-group">
                {{form.submit(class="btn btn-outline-info")}}
            </div>
        </form>
    </div>

    <div class="border-top pt-3">
        <small class="text-muted">
            Don't Have An Account? <a class="ml-2" href="{{url_for('auth.register')}}">Register</a>
        </small>
    </div>
</div>
{% endblock content %}

app/templates/user_page.jinja
{% extends "base.jinja" %}

{% block content %}

<h3>{{ user.username }}'s Page</h3>
<h1>My Posts</h1>
{% for post in user.posts %}
  <p>{{ post.body }}</p>  <small>{{ post.timestamp }}</small>
{% endfor %}

<h1>My Car Collection</h1>
{% for add_car in user.cars %}
  <ol>
  <p>Make: {{ add_car.make }}, Model: {{add_car.model}}, Year: {{add_car.year}}</p>
  </ol>
  
{% endfor %}

{% endblock %}